apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
type: Opaque
stringData:
  applicationKey: {{ .Values.applicationKey | quote }}
  applicationSecret: {{ .Values.applicationSecret | quote }}
  applicationConsumerKey: {{ .Values.applicationConsumerKey | quote }}
