usersDatabase: ENC[AES256_GCM,data:/kDXoG00YG6phgaFYiczBpfUbmXVg6MRcx7Uo29r72v9StfiiQmbOtDNevD8Avy11dRfyKpgvQSSQuiFq345Q3tK3oXEYHOuidDwxm1+4YgIxqLkhL/Um92GGmw8eHu2WcEqlwxtMElTEfCUoX7kuRWVdN8eNg4LSDK43NX+R8o6idUsxJB/WEdhXyVY5nUx25MJT3gH295d8QUxnx/SSJ6NSPpnpKzl4uXppa9+gYKp0LcMiJD8pliYYOB3QTt5TVxacDYBGd/CeX1VULfB3A1OtnGIeFe0vfF+VMRgoYN4k+il7Pq9DRS/hTjVjOG0IO+DjjfTRrwC9Wsxrh1woV6TjZbwfYu2P4gPeMf3UpBr3V4O8PZScqgM2aZqWw7s3gZ58fKgyljN1HUPqtjIh9/lU7i8+4SPH1J2p40cKfzt1RE=,iv:xDgJV+NnneR7h2Llbe1x0lysf0TT57XeWDysDfzsNzY=,tag:k95EV19Ca6CaQcObF5cDUQ==,type:str]
sops:
    age:
        - recipient: age184fnlwvmqnepnjwtxptquyf62ejasynvfujs0tgpts7vzavj5glqmmn23e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM0pDTjhXSDVDaFBqVjE4
            dzVBV0IxUXpyQldDb2pSc3QyZnNxRmhCakNBCmMwZ1NnQ3Z3MTlEWWx5QnU1V2hP
            bFZRdEcwRnJvNzgyVVpsRnZ4OTh2elEKLS0tIHJNQStaUWNqY3BGaDFoSUVsWlVM
            cE5TemxjaVVBOVdBSnBEQy9tRXhINFkKT927G3yCNhFU+1NJm7iP3d2j7iw4cSTs
            /bB2USXugq4inJ/WFZ/FwjUj8JOI2XLc7HOm9y0IRZqhCQXHvuttgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T20:29:31Z"
    mac: ENC[AES256_GCM,data:7EQOrISMJ+uCKzJz5HufXh7WHu3czGWmQGEKM+URi/8gizSgxP1SmpvxjXvQe+jkz1QSSc3kRyDhxMxcdITKmwOcvQ+oJXWqeQNybpAJL3BHkI+NxzO4CYDq8vmIHgT5nNPJmfIBBzzKtICYSGesRQsZDK0ifUHrkGG11K63pAk=,iv:1+wRl23xHNvoKt6qsGD+qFED/PYmyVjymCcaw7QdD+Q=,tag:sAAsOnqeUMufJAKp1WCXFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
