usersDatabase: ENC[AES256_GCM,data:YgLtAGRy4T4ajLxJeGYOfUb1jNWZiY8roJf1t2MmDIi9G0x7EqVSVVuLGrpiSS/37tTRuMkPcOx3WF7fJlIbh83SZdFSLjUURV0mA3VDsSGvLDAVWwHv25OdWqdKZn4kUuk/9o8oWf10ScbZ9nvXj+lv0jMjS9keabVs/zam9VKE9ER3F384zeKpr5pH3Mq6AzYVODhv0PqMiSOtVC+U+5faQpwYHfnJKo7VEOl/SnUHka8VjMUfYdK7xBwIbBJfLx8xYuoJGWb4dxj3NIwGo7vEJ9mo4hi6q1WF4vukirCysuHdUPP8Fb2605WI6ayDRFHyBZKQUEVrUOhDLmx7XmtcFhz/1pvxY20wLVFjNglL+urlbx6bpOYTjD069qDToo0luTsgO+Z7aWF8CHuk1rRviaXu28tfomYj7HnEGh3QPTeEko9wKYzB2g==,iv:HRBrIxRi9RWqE0XcLSeTRhsxPn+QDWr0L29FSVEZb6E=,tag:ArvyaGz+ldzuDdl5lsmrDg==,type:str]
sops:
    age:
        - recipient: age184fnlwvmqnepnjwtxptquyf62ejasynvfujs0tgpts7vzavj5glqmmn23e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OTJJc256QWR6WXZXRjhT
            eGpXMDI5cWo5N2hHekhScnZoeXdINFlUaWpZCm1hRDRBTEgrL2VmQk1IWmpQd2Mz
            Q1V6NnpEWFJNOWhTbFRjdTBaZy9jNDQKLS0tIDI3cHNaNm5ud29QVS93Q1hIK0RQ
            dnlGY2U3MTNRQVZmMmExdkVkTVUrQVkKQUs9c/hAKymvDEh6ySYOSLQYGLn8RrBo
            RqZFYbnpaWM65rzi8aqpZC+3ajY1knwFAwpTjiJLa0j3iS1L4syn6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T17:39:15Z"
    mac: ENC[AES256_GCM,data:QrkEongskgVDsKNyLzHPEAiT+7BckAYxKUjEzehSqCRyYwGARfjD0X46M/IBpOWSRBLrpVfZ4SXmpxRss9im7D0JX3RDHGimyR2Np2FxospK57sBemXpdkt3+AYTiNEC2e1uUQvu4KLHC7ukUb+dVpBxJMhmcgnZjp0Jg1/qYsE=,iv:OuYGENZ5XVCr7950piLx1x8iIFU8mCdt+JiauPMMYiU=,tag:nZPh8ozlk2sdBgf+rvS0/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
