usersDatabase: ENC[AES256_GCM,data:MevH28bdge94H1bhMrqreCYfphWh/IU2hdSFq3mzpT8RjeaQIxfWFTK0yw8J4LnZs1qR4jSjYpvhMsB0/Y/J6PlJQrop2FXjwLaqGy7QHS4Bk1TQzzcAo7f5Ef90oK7pu/TtRO+/Y055BlmNd1MD2F/8fpJZsSjRFeBNsqD1AKjA2RrKavHyr7oMPWqnvVP50lzpKTb1V6Qgewb14KgE1+Bwqicc4s3xQLGe9u9vUogs7emwZod9cEd+xuQeZgFHVM7KEfjfqe42ZM6s/6RCCMRFBHm2dT7h8ibTtJ6NAJx9pHNWgnzTlZcNmOn3KBKbNE/dOkvMB7CsS61uuNg/dLG11Csl0r1izhHffDjyOPX7V8HIjVoQar3zrp8K5PKf64MjvkPbu4r9WmCETuEnN4egsrKoYxz4gqWA58TGNIDbC+s=,iv:viHz1fW1lHq8FztfPC1r6LyHzWEaZTCiE5VHjSvrboQ=,tag:96sVP/3AX6iaKi45yLqmKw==,type:str]
sops:
    age:
        - recipient: age184fnlwvmqnepnjwtxptquyf62ejasynvfujs0tgpts7vzavj5glqmmn23e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvM0pDTjhXSDVDaFBqVjE4
            dzVBV0IxUXpyQldDb2pSc3QyZnNxRmhCakNBCmMwZ1NnQ3Z3MTlEWWx5QnU1V2hP
            bFZRdEcwRnJvNzgyVVpsRnZ4OTh2elEKLS0tIHJNQStaUWNqY3BGaDFoSUVsWlVM
            cE5TemxjaVVBOVdBSnBEQy9tRXhINFkKT927G3yCNhFU+1NJm7iP3d2j7iw4cSTs
            /bB2USXugq4inJ/WFZ/FwjUj8JOI2XLc7HOm9y0IRZqhCQXHvuttgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T21:56:44Z"
    mac: ENC[AES256_GCM,data:9GMMZl2CjQ7Y6XjV+y6JmQ1Pzvyv0tos1nfzqQ/h/4rdfgvO3rPaWg+9gMKsAQiTbX7otzaMS3dJcPSbDss4OiDJS08V4JvLOrdheeHhZBp9nQDtYIw7URAMsFnVczdjHExtooauU6TbSIflbChxLl4n0YBZ5sl5GGjWH+WEdDU=,iv:Qt7JjEG9jj1bZrYQPD1pZg8k4d7kEV64XQb1bTNpxCc=,tag:4k0/a/n8y7Vz6WSoc16jSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
