applicationKey: ENC[AES256_GCM,data:IcrcidqXeutIJjB6kJfZzg==,iv:kZHLNIOZ6rO/QVwr5D6cMLVMcgvKkCblDjpzIYIHNyk=,tag:RYQOE0Zbe7hDTVXPSWa+sA==,type:str]
applicationSecret: ENC[AES256_GCM,data:szryV1QO8ZM7rKXEHZZURrK5n6l7N7CspT0su5P3P2E=,iv:lSxNButQ++6wtY9znrSUAsc5hktOhnPPeP8l1etln0Q=,tag:OPq9yc59PzP5pBw1zV7Q6w==,type:str]
applicationConsumerKey: ENC[AES256_GCM,data:NdCWzEhOx3osbI0YpCgVncFo2EDxyTA1pkyZj4lvRMY=,iv:hJ2mMoMVXtS5795bHSRlTAJpPvNAXX+WKZnIet2/UFA=,tag:Rlpg9L3nocHcv5abzNDq9A==,type:str]
sops:
    age:
        - recipient: age184fnlwvmqnepnjwtxptquyf62ejasynvfujs0tgpts7vzavj5glqmmn23e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQVI3MkZBOFp1b0tFUk9i
            NkZUT2lvODhXL254K1pJRlV1SVZJUzN1UUNNClN5N0JpMkl5cCtzZDNlZ3NnczlT
            UG5lR3pYSFV3MDk3WGdadmJHUEQzWVUKLS0tIDlFdWMwTExJTk1WcytqZDdGTTd1
            ckZEdlBobVB3MkNBS2NLd2hkcjhhK3cKiflZqcgF7nxmGu4A1/s7ASqLiq711yY+
            kNIBKHjg523nVsDVQV7n1gcC9Jt2sMBPVyWv+m5MhIzi9BzMjpQvDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T22:34:32Z"
    mac: ENC[AES256_GCM,data:/SDJO3pfnZpGFMGmbCdrvVeiHSwYTXp2BgngNDfHRquqjsz9n7Avgc5jLofPC7mZr1K4kL1vEKY1INtu0Mn2F+GSbKReSiQGu2k/JGqOBfCenesJlBHIO2hNxsNTacKGSV42CD88GJ3/0mvkKpepDnPXqrvMNCk7tfI6o5hinVw=,iv:y+gnChj2Quyc3Z5XQ+jW074//SDLcqLchssGRqvanEI=,tag:X1U3ghsFcCKjvr4EpauKtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
