[changelog]
header = "# Changelog\n"
body = """
{% for commit in commits %}\
- `{{ commit.group }}` {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/VictorMalodPortfolio/Homelab/commit/{{ commit.id }}))
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^docs: update CHANGELOG", skip = true },
  { message = "^feat", group = "feat" },
  { message = "^fix", group = "fix" },
  { message = "^docs", group = "docs" },
  { message = "^refactor", group = "refactor" },
  { message = "^ci", group = "ci" },
  { message = "^build", group = "build" },
  { message = "^chore", group = "chore" },
  { message = "^test", group = "test" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
