apiVersion: v1
kind: Pod
metadata:
  name: dummy-insecure
spec:
  containers:
    - name: app
      image: nginx
      securityContext:
        privileged: true
        runAsUser: 0
      resources: {}
