service:
  type: LoadBalancer

ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-victor-malod-ovh-tls
