apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
data:
  admin.enabled: "false"
  helm.valuesFileSchemes: secrets, https
  url: https://{{ .Values.host }}
  oidc.config: |
    name: Authelia
    issuer: https://auth.victor-malod.ovh
    clientID: argocd
    clientSecret: $argocd-oidc-secret:oidc.authelia.clientSecret
    requestedScopes:
      - openid
      - groups
      - email
      - profile
    enableUserInfoGroups: true
    userInfoPath: /api/oidc/userinfo
