apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  oidc.authelia.clientSecret: {{ .Values.oidcClientSecret | quote }}
