oidcClientSecret: ENC[AES256_GCM,data:tw2jPHW3gLoytHUk/yDfL9WzLZXoryuTfR+ceDBm/82VX9CPkD0ABSvUgEnMqPQUR2KDpT4Cq/noocQhtShOzA==,iv:Hq1Bb7t/rKIwc7uClAF2ksjczCVFQ57iHZDfjtKQkbI=,tag:E07xf4lP1vf1fByJkRihkg==,type:str]
sops:
    age:
        - recipient: age184fnlwvmqnepnjwtxptquyf62ejasynvfujs0tgpts7vzavj5glqmmn23e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bEtlcmdUNTRFeDhQaDJD
            ZlV1cVkwWkFXcnl0NW1wSG9PNjlhNzhNYXpjCm9EWHV1S3I2Nmw2T0RacFdMc05p
            MHpLL0JkS3hGRm5OUFhyWFNMb0dXYkUKLS0tIEVqU1lWM2FxaG9wVU96OUxuREgy
            NVNPdDZyaXpVV1o3ZEtwTnkzM2ZwaEEK/oTX2wQPpEY/QIv9rJDwKVIfLFQjM97t
            GTyK+bAal6wt6x3Nzb4hHSAEOAGYzj8z7BGokDgsRj9vN7wtKxhyvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T22:11:57Z"
    mac: ENC[AES256_GCM,data:8JNHoUqe2xiImsuKVZrh9Y+5ANPRNqe7UygJ1U8CmkXzU3/E+bxTbnyQ1ABhsJbAV/33jihc3iTDUAtsxgUJqSK1YKo+Sen9DX9HFpEiGtEaXSdB0Z/6EJZcjtDAaoD0Xx5yhG/JdWjssNUPdQE1Dn/DtprMe8uZNAd8wjnNQgo=,iv:SY6vBenWglESKDpvial3WGXXogNmJaJxoR5/vTpqyBA=,tag:OgwZXvpV7J6G3MFW8tr0iQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
